### ISSUE TITLE
No burp plugin

### ISSUE THREAD

**Issue by 1nc00r3ct** [mateuszk87/BadIntent#3]
Hi, Is there any way you can provide the burp plugin directly via any link or something?

**Comment by mateuszk87** [comment]
Sure, check the releases section. There you can find the jar file which can be used by burp's extender.

**Comment by mateuszk87** [comment]
https://github.com/mateuszk87/BadIntent/releases

**Comment by 1nc00r3ct** [comment]
Thank you
